import { StateGraph, START, END } from "@langchain/langgraph";
import { AgentStateAnnotation, AgentStateType, OpportunityContext } from "./state.js";
import {
  getProduct,
  getInventory,
  getSales,
  getRevenue,
  getProductCombinations,
} from "./tools/index.js";
import { queryGroqForProposal } from "./groq.js";
import { aiProposalSchema } from "./schema.js";

async function contextGatheringNode(state: AgentStateType): Promise<Partial<AgentStateType>> {
  const { opportunity, merchantId } = state;
  const context: OpportunityContext = {};

  try {
    const productId = String(opportunity.data?.productId ?? "");
    const variantId = String(opportunity.data?.variantId ?? "");

    const [product, inventory, sales, overview] = await Promise.all([
      productId ? getProduct(merchantId, productId) : null,
      variantId ? getInventory(merchantId, variantId) : null,
      getSales(merchantId, variantId || undefined, productId || undefined),
      getRevenue(merchantId),
    ]);

    if (product) {
      context.product = {
        id: product.id,
        name: product.name,
        description: product.description,
        status: product.status,
      };
      context.variants = product.variants.map((v) => ({
        id: v.id,
        sku: v.sku,
        name: v.name,
        price: v.price,
        inventory: v.inventory
          ? { quantity: v.inventory.quantity, reserved: v.inventory.reserved }
          : null,
      }));
    }

    if (inventory?.variant) {
      context.variants = [
        {
          id: inventory.variant.id,
          sku: inventory.variant.sku,
          name: inventory.variant.name,
          price: inventory.variant.price,
          inventory: {
            quantity: inventory.quantity,
            reserved: inventory.reserved,
          },
        },
      ];
    }

    context.salesSummary = sales;
    context.storeOverview = {
      totalRevenue: overview.totalRevenue,
      totalOrders: overview.totalOrders,
      activeProducts: overview.activeProducts,
    };

    if (opportunity.type === "CROSS_SELL" && productId) {
      context.productCombinations = await getProductCombinations(
        merchantId,
        productId
      );
    }
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : "Failed to gather context";
    return {
      context,
      errors: [errorMsg],
    };
  }

  return {
    context,
  };
}

async function reasoningNode(state: AgentStateType): Promise<Partial<AgentStateType>> {
  const { opportunity, context } = state;

  try {
    const proposal = await queryGroqForProposal(opportunity, context);
    return {
      proposal,
    };
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : "Reasoning node failure";
    return {
      errors: [errorMsg],
    };
  }
}

async function validationNode(state: AgentStateType): Promise<Partial<AgentStateType>> {
  const { proposal } = state;

  if (!proposal) {
    return {
      errors: ["No proposal generated by AI reasoning"],
    };
  }

  const result = aiProposalSchema.safeParse(proposal);
  if (!result.success) {
    return {
      errors: [
        `AI proposal schema validation failed: ${result.error.issues.map((i) => i.message).join(", ")}`,
      ],
    };
  }

  return {
    proposal: result.data,
  };
}

export function createOpportunityAgent() {
  const workflow = new StateGraph(AgentStateAnnotation)
    .addNode("contextGathering", contextGatheringNode)
    .addNode("reasoning", reasoningNode)
    .addNode("validation", validationNode)
    .addEdge(START, "contextGathering")
    .addEdge("contextGathering", "reasoning")
    .addEdge("reasoning", "validation")
    .addEdge("validation", END);

  return workflow.compile();
}

export async function runOpportunityAgent(
  opportunity: AgentStateType["opportunity"],
  merchantId: string
) {
  const agent = createOpportunityAgent();
  const result = await agent.invoke({
    opportunity,
    merchantId,
  });

  return {
    opportunity: result.opportunity,
    context: result.context,
    proposal: result.proposal,
    errors: result.errors,
  };
}
